### PR TITLE
add Linux AppImage

### PR DESCRIPTION
**Pull request by nerdCopter**
* build Linux AppImage executable.
* may need validation.

### CODE REVIEW

**Comment by nerdCopter** [comment]
i was able to produce a working `release/ExpressLRS Configurator-1.2.5.AppImage`, although it contains a space in the filename.

This PR should be validated because my environment fails after the pacman package, which is likely unrelated :
```
  • electron-builder  version=22.10.5 os=5.10.0-9-amd64
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=release/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@serialport/bindings@9.0.7 platform=linux arch=x64
  • rebuilding native dependency  name=@serialport/bindings version=9.0.7
  • packaging       platform=linux arch=x64 electron=12.0.2 appOutDir=release/linux-unpacked
  • Unpacking electron zip  zipPath=undefined
  • building        target=zip arch=x64 file=release/expresslrs-configurator-1.2.5.zip
  • building        target=AppImage arch=x64 file=release/ExpressLRS Configurator-1.2.5.AppImage
  • building        target=deb arch=x64 file=release/expresslrs-configurator_1.2.5_amd64.deb
  • building        target=pacman arch=x64 file=release/expresslrs-configurator-1.2.5.pacman
  ⨯ cannot execute  cause=exit status 1
```

**Comment by jurgelenas** [comment]
Hey @nerdCopter, can you confirm that firmware flashing still works with this image?

**Comment by jurgelenas** [comment]
I also think that we need to bundle git & python with AppImage since you are not able to specify system dependencies for AppImage builds?

**Comment by nerdCopter** [comment]
* i will test flashing once i receive my hardware.
* As far as bundling, ... such is beyond my ability. :( (i'm thinking electron-builder automagically does what it needs)
* The resultant AppImage was usable and it compiled binaries, of course maybe it simply falls-back to locally installed tools.
* https://drive.google.com/file/d/1OoTD3wwMrPmcWoRv2JnS93jlZkwD1rKp/view?usp=sharing
* if this is helpful in any way:
image
image

**Comment by jurgelenas** [comment]
We need to figure out how to bundle python and git with AppImage. Otherwise, this distribution format does not make much sense. I was looking into this before but was not able to find an easy way to do it.

It could be the case, that we need to perform the same thing as we do for macOS and Windows - bundle files manually: https://github.com/ExpressLRS/ExpressLRS-Configurator/tree/master/dependencies.

**Comment by nerdCopter** [comment]
thanks @jurgelenas , i'll close this PR and jsut build local un-bundled AppImages for personal needs.

**Comment by jurgelenas** [comment]
@nerdCopter it might be possible to create app image with required dependencies using: https://github.com/AppImage/pkg2appimage

**Comment by nerdCopter** [comment]
* further evidence that this is was not a quick & simple (not viable) as-is.
* it worked on one machine but not another; therefore, some external dependencies are not met and possibly not listed.




```
$ ./ExpressLRS\ Configurator-1.3.2.AppImage 
{
  context: {
    PATH: '/tmp/.mount_ExpresJz7CzY:/tmp/.mount_ExpresJz7CzY/usr/sbin:/home/USERNAME/.yarn/bin:/home/USERNAME/.config/yarn/global/node_modules/.bin:/home/USERNAME/.local/bin:/home/USERNAME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/USERNAME/.gem/ruby/2.5.0/bin/'
  },
  level: 'info',
  message: 'path'
}
{ context: undefined, level: 'info', message: 'trying to get port' }
{
  context: { port: 3500 },
  level: 'info',
  message: 'received unused port'
}
{ context: undefined, level: 'info', message: 'starting server...' }
{
  context: {
    PATH: '/tmp/.mount_ExpresJz7CzY:/tmp/.mount_ExpresJz7CzY/usr/sbin:/home/USERNAME/.yarn/bin:/home/USERNAME/.config/yarn/global/node_modules/.bin:/home/USERNAME/.local/bin:/home/USERNAME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/USERNAME/.gem/ruby/2.5.0/bin/'
  },
  level: 'info',
  message: 'local api server PATH'
}
{
  context: undefined,
  stack: [ undefined ],
  level: 'error',
  message: "createWindow error Error: ENOENT: no such file or directory, scandir '/tmp/.mount_ExpresJz7CzY/devices'"
}
{
  context: undefined,
  stack: [ undefined ],
  level: 'error',
  message: "handling fatal error: Error: ENOENT: no such file or directory, scandir '/tmp/.mount_ExpresJz7CzY/devices'"
}

```

**Pull request closed without merging**
